version: '3'
services:
  tf-serving-server:
    container_name: ecg_cnn
    image: tensorflow/serving
    ports:
      - "8501:8501"
      - "8500:8500"
    volumes:
      - ./export_tf/ecg/cnn:/models/cnn
    environment:
      - MODEL_NAME=cnn
    networks:
      - tf_serving
  tf-serving-client:
    build:
      context: ./tf_client
      dockerfile: Dockerfile.tf_client
    container_name: tf-serving-client
    networks:
      - tf_serving
    ports:
      - "5000:5000"
    environment:
      - TF_SERVER_NAME=tf-serving-server
      - TF_SERVER_PORT=8501
      - FLASK_SERVER_NAME=0.0.0.0
      - FLASK_SERVER_PORT=5000
      - FLASK_DEBUG=1
    depends_on:
      - tf-serving-server
networks:
  tf_serving:
    driver: bridge